spring:
  datasource:
    url: jdbc:mysql://database-1.cfdmibvojvgm.ap-northeast-2.rds.amazonaws.com:3306/test?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: ${RDS_ID}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database : mysql
#    database-platform : hibernate.dialect.MySQl5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_OAUTH_ID}
            clientSecret: ${GOOGLE_OAUTH_PW}
            scope:
              - email
              - profile
config:
  domain: http://seb41-main-022.s3-website.ap-northeast-2.amazonaws.com/
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: utest3912@gmail.com # admin mail address
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30     # 30분 (0.5시간)
  refresh-token-expiration-minutes: 420   # 420분  (7시간)